"""Ensure unique report cards

Revision ID: 8899af719586
Revises: a92a2bb2e760
Create Date: 2026-10-05 15:23:26.398734
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8899af719586'
down_revision: Union[str, None] = 'a92a2bb2e760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report_cards") as batch_op:
        batch_op.create_unique_constraint(
            "uq_report_cards_student_term_subject",
            ["student_id", "term", "subject"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report_cards") as batch_op:
        batch_op.drop_constraint(
            "uq_report_cards_student_term_subject",
            type_="unique",
        )
    # ### end Alembic commands ###
